version: '3.8'
services:
  mysql-1:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: db_banco
      MYSQL_USER: root
    ports:
      - "3307:3306"

  banco-app-1:
    image: banco-app
    depends_on:
      - mysql-1
    ports:
      - "9090:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-1:3306/db_banco?createDatabaseIfNotExist=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root