version: "3"
services:
  banco-app:
    image: springboot-banco
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/db_banco?useSSL=false
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db_banco
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: